name: flake8 lint
on:
  push:
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-20.04
    name: flake8 lint
    steps:
      - name: Setup python for flake8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: actions/checkout@v3
      - name: Install nox
        run: python -m pip install nox
      - name: Setup flake8
        run: nox --notest -e flake8
      - name: Run flake8
        run: nox -e flake8
