name: test
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.netapi }} - ${{ matrix.salt }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        netapi:
          - "cherrypy"
          - "tornado"
        salt:
          - "v3006.5"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install setuptools_scm
        run: python -m pip install setuptools_scm

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libc6-dev libffi-dev gcc git openssh-server libzmq3-dev
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Install Test Requirements
        env:
          SALT_REQUIREMENT: salt==${{ matrix.salt }}
        run: |
          nox --force-color -e tests-3 --install-only

      - name: Test
        env:
          SALT_REQUIREMENT: salt==${{ matrix.salt }}
          SKIP_REQUIREMENTS_INSTALL: YES
        run: |
          nox --force-color -e tests-3 -- -vv tests/
